FROM public.ecr.aws/docker/library/node:20-alpine AS frontend-builder

WORKDIR /app

ARG VITE_NETWORK_MODE
ARG VITE_BACKEND_URL
ARG VITE_BACKEND_API_URL
ARG VITE_ARBITRUM_MAINNET_RPC_URL
ARG VITE_OPTIMISM_MAINNET_RPC_URL
ARG VITE_ETHEREUM_MAINNET_RPC_URL
ARG VITE_XDC_MAINNET_RPC_URL
ARG VITE_ARBITRUM_SEPOLIA_RPC_URL
ARG VITE_OPTIMISM_SEPOLIA_RPC_URL
ARG VITE_ETHEREUM_SEPOLIA_RPC_URL
ARG VITE_BASE_SEPOLIA_RPC_URL
ARG VITE_GENESIS_CONTRACT_ADDRESS
ARG VITE_NOWJC_CONTRACT_ADDRESS
ARG VITE_PROFILE_GENESIS_ADDRESS
ARG VITE_LOWJC_CONTRACT_ADDRESS
ARG VITE_ARBITRUM_GENESIS_ADDRESS
ARG VITE_NATIVE_ARB_LOWJC_ADDRESS
ARG VITE_NATIVE_ARB_ATHENA_ADDRESS
ARG VITE_LAYERZERO_OPTIONS_VALUE
ARG VITE_POLYGON_RPC_URL

ENV VITE_NETWORK_MODE=$VITE_NETWORK_MODE \
    VITE_BACKEND_URL=$VITE_BACKEND_URL \
    VITE_BACKEND_API_URL=$VITE_BACKEND_API_URL \
    VITE_ARBITRUM_MAINNET_RPC_URL=$VITE_ARBITRUM_MAINNET_RPC_URL \
    VITE_OPTIMISM_MAINNET_RPC_URL=$VITE_OPTIMISM_MAINNET_RPC_URL \
    VITE_ETHEREUM_MAINNET_RPC_URL=$VITE_ETHEREUM_MAINNET_RPC_URL \
    VITE_XDC_MAINNET_RPC_URL=$VITE_XDC_MAINNET_RPC_URL \
    VITE_ARBITRUM_SEPOLIA_RPC_URL=$VITE_ARBITRUM_SEPOLIA_RPC_URL \
    VITE_OPTIMISM_SEPOLIA_RPC_URL=$VITE_OPTIMISM_SEPOLIA_RPC_URL \
    VITE_ETHEREUM_SEPOLIA_RPC_URL=$VITE_ETHEREUM_SEPOLIA_RPC_URL \
    VITE_BASE_SEPOLIA_RPC_URL=$VITE_BASE_SEPOLIA_RPC_URL \
    VITE_GENESIS_CONTRACT_ADDRESS=$VITE_GENESIS_CONTRACT_ADDRESS \
    VITE_NOWJC_CONTRACT_ADDRESS=$VITE_NOWJC_CONTRACT_ADDRESS \
    VITE_PROFILE_GENESIS_ADDRESS=$VITE_PROFILE_GENESIS_ADDRESS \
    VITE_LOWJC_CONTRACT_ADDRESS=$VITE_LOWJC_CONTRACT_ADDRESS \
    VITE_ARBITRUM_GENESIS_ADDRESS=$VITE_ARBITRUM_GENESIS_ADDRESS \
    VITE_NATIVE_ARB_LOWJC_ADDRESS=$VITE_NATIVE_ARB_LOWJC_ADDRESS \
    VITE_NATIVE_ARB_ATHENA_ADDRESS=$VITE_NATIVE_ARB_ATHENA_ADDRESS \
    VITE_LAYERZERO_OPTIONS_VALUE=$VITE_LAYERZERO_OPTIONS_VALUE \
    VITE_POLYGON_RPC_URL=$VITE_POLYGON_RPC_URL

# Install frontend deps and build
COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# ── Production image ──────────────────────────────────────────────────────────
FROM public.ecr.aws/docker/library/node:20-alpine

WORKDIR /app

# Copy built frontend from builder stage
COPY --from=frontend-builder /app/dist ./dist

# Setup backend
WORKDIR /app/backend
COPY backend/package*.json ./
RUN npm ci --production
COPY backend ./

EXPOSE 8080
ENV PORT=8080
CMD ["node", "server.js"]
